# Generated by Django 2.2.3 on 2019-07-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rcuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rcuser',
            name='telegram_chat',
        ),
        migrations.RemoveField(
            model_name='rcuser',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='rcuser',
            name='telegram_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.TelegramUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.TelegramChat'),
            preserve_default=False,
        ),
    ]
